---
title: "organoid_composition"
author: "Nate Mullin"
date: "9/30/2022"
output: html_document
---

```{r setup, include=FALSE}
library(Seurat)
library(cowplot)
library(dplyr)
library(tidyverse)
library(EnhancedVolcano)
library(RColorBrewer)
library(ggplot2)
library(ggpubr)
library(ggcorrplot)

set.seed(1234)

```

```{r}
load(".../cluster_annotation/organoid_all_tp.RData")
```

```{r}
# plot counts
line_cols <- c("#377eb8", "#e41a1c", "#4daf4a")

cell_counts <- as.data.frame(table(organoid_all_tp$donor_annotation, organoid_all_tp$line, organoid_all_tp$timepoint))
cell_counts <- as_tibble(cell_counts)
cell_props <- cell_counts %>%
              group_by(Var2, Var3) %>%
              mutate(prop = Freq/sum(Freq)*100)

ct <- levels(cell_props$Var1)
ct
output_plots <- list()
for (i in ct) { 
  output_plots[[i]] <- cell_props %>% 
                        dplyr::filter(Var1 == i) %>% 
                        ggplot(aes(x=Var3, y=prop, group=Var2)) +
                        geom_line(aes(color=Var2, alpha = 0.5), )+
                      scale_color_manual(values=line_cols) +
                        geom_point()+
                        ggtitle(i) + xlab(label = "timepoint") + ylab(label = "proportion") + 
                        theme_half_open()
}

cell_props %>% group_by(Var2, Var3) %>% summarise(sum(prop))

cell_props %>% group_by(Var2, Var3) %>% summarise(sum(Freq))
sum(cell_props$Freq)

write.csv(cell_props, file = "cell_props.csv")

pdf("cell_type_by_time.pdf", width=12, height=22)
ggarrange(plotlist = output_plots,
          common.legend = T, legend = "right", ncol = 3, nrow = 8)
dev.off()
```